# -*- coding: utf-8 -*-
"""Lab_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f2MxvF55UMR9_Q-XXnppANePHU423W8r
"""

calc=input('Please enter your calculation. ')
a,b,c=calc.split(' ')

a=int(a)
b=b.lower().strip()
c=int(c)

if b=='*':
  print(a*c)
elif b=='+':
  print(a+c)
elif b=='-':
  print(a-c)
elif b=='/':
  print(a/c)
else:
  print('Invalid')

def convert_time():
  time=input("What time is it? ")
  time1,time2,time3 = time.split()
  a= float (time1)
  b= time2 
  c= float (time3)
  return (a+c/ 60)

time4 = convert_time()
if time4 >=8.0 and time4 <=10.0:
  print('Reading Lesson')
elif time4 >=10.0 and time4 <=12.0:
  print('Math Lesson')
elif time4 >= 12.0 and time4<=13.0:
  print('Lunch time')
elif time4 >= 1.0 and time4<= 2.0:
  print('Music Lessons')
else:
  print('Home time')